/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangun;

import java.io.File;
import javax.swing.JOptionPane;
import static bangun.Strings.*;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mateusz
 */
public class ChooseWeapons extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    public ChooseWeapons() {
        initComponents();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox63 = new javax.swing.JCheckBox();
        jCheckBox64 = new javax.swing.JCheckBox();
        jCheckBox65 = new javax.swing.JCheckBox();
        jCheckBox66 = new javax.swing.JCheckBox();
        jCheckBox67 = new javax.swing.JCheckBox();
        jCheckBox68 = new javax.swing.JCheckBox();
        jCheckBox69 = new javax.swing.JCheckBox();
        jCheckBox70 = new javax.swing.JCheckBox();
        jCheckBox71 = new javax.swing.JCheckBox();
        jCheckBox72 = new javax.swing.JCheckBox();
        jCheckBox73 = new javax.swing.JCheckBox();
        jCheckBox74 = new javax.swing.JCheckBox();
        jCheckBox75 = new javax.swing.JCheckBox();
        jCheckBox76 = new javax.swing.JCheckBox();
        jCheckBox77 = new javax.swing.JCheckBox();
        jCheckBox78 = new javax.swing.JCheckBox();
        jCheckBox79 = new javax.swing.JCheckBox();
        jCheckBox80 = new javax.swing.JCheckBox();
        jCheckBox81 = new javax.swing.JCheckBox();
        jCheckBox82 = new javax.swing.JCheckBox();
        jCheckBox83 = new javax.swing.JCheckBox();
        jCheckBox84 = new javax.swing.JCheckBox();
        jCheckBox85 = new javax.swing.JCheckBox();
        jCheckBox86 = new javax.swing.JCheckBox();
        jCheckBox87 = new javax.swing.JCheckBox();
        jCheckBox88 = new javax.swing.JCheckBox();
        jCheckBox89 = new javax.swing.JCheckBox();
        jCheckBox90 = new javax.swing.JCheckBox();
        jCheckBox91 = new javax.swing.JCheckBox();
        jCheckBox92 = new javax.swing.JCheckBox();
        jCheckBox93 = new javax.swing.JCheckBox();
        jCheckBox94 = new javax.swing.JCheckBox();
        jCheckBox95 = new javax.swing.JCheckBox();
        jCheckBox96 = new javax.swing.JCheckBox();
        jCheckBox97 = new javax.swing.JCheckBox();
        jCheckBox98 = new javax.swing.JCheckBox();
        jCheckBox99 = new javax.swing.JCheckBox();
        jCheckBox100 = new javax.swing.JCheckBox();
        jCheckBox101 = new javax.swing.JCheckBox();
        jCheckBox102 = new javax.swing.JCheckBox();
        jCheckBox103 = new javax.swing.JCheckBox();
        jCheckBox104 = new javax.swing.JCheckBox();
        jCheckBox105 = new javax.swing.JCheckBox();
        jCheckBox106 = new javax.swing.JCheckBox();
        jCheckBox107 = new javax.swing.JCheckBox();
        jCheckBox108 = new javax.swing.JCheckBox();
        jCheckBox109 = new javax.swing.JCheckBox();
        jCheckBox110 = new javax.swing.JCheckBox();
        jCheckBox111 = new javax.swing.JCheckBox();
        jCheckBox112 = new javax.swing.JCheckBox();
        jCheckBox113 = new javax.swing.JCheckBox();
        jCheckBox114 = new javax.swing.JCheckBox();
        jCheckBox115 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(odkoduj(maintitle));

        jScrollPane1.setVerifyInputWhenFocusTarget(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(210, 653));

        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(18, 18));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox2.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox2.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox2.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox3.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox3.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox3.setPreferredSize(new java.awt.Dimension(18, 18));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox4.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox4.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox4.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox5.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox5.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox5.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox6.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox6.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox6.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox7.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox7.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox7.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox8.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox8.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox8.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox9.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox9.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox9.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox63.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox63.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox63.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox63.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox64.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox64.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox64.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox64.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox65.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox65.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox65.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox65.setPreferredSize(new java.awt.Dimension(18, 18));
        jCheckBox65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox65ActionPerformed(evt);
            }
        });

        jCheckBox66.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox66.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox66.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox66.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox67.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox67.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox67.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox67.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox68.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox68.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox68.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox68.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox69.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox69.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox69.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox69.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox70.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox70.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox70.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox70.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox71.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox71.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox71.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox71.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox72.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox72.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox72.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox72.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox73.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox73.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox73.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox73.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox74.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox74.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox74.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox74.setPreferredSize(new java.awt.Dimension(18, 18));
        jCheckBox74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox74ActionPerformed(evt);
            }
        });

        jCheckBox75.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox75.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox75.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox75.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox76.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox76.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox76.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox76.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox77.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox77.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox77.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox77.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox78.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox78.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox78.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox78.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox79.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox79.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox79.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox79.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox80.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox80.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox80.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox80.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox81.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox81.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox81.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox81.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox82.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox82.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox82.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox82.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox83.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox83.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox83.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox83.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox84.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox84.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox84.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox84.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox85.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox85.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox85.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox85.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox86.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox86.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox86.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox86.setPreferredSize(new java.awt.Dimension(18, 18));
        jCheckBox86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox86ActionPerformed(evt);
            }
        });

        jCheckBox87.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox87.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox87.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox87.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox88.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox88.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox88.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox88.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox89.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox89.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox89.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox89.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox90.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox90.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox90.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox90.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox91.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox91.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox91.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox91.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox92.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox92.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox92.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox92.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox93.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox93.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox93.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox93.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox94.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox94.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox94.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox94.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox95.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox95.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox95.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox95.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox96.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox96.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox96.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox96.setPreferredSize(new java.awt.Dimension(18, 18));
        jCheckBox96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox96ActionPerformed(evt);
            }
        });

        jCheckBox97.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox97.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox97.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox97.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox98.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox98.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox98.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox98.setPreferredSize(new java.awt.Dimension(18, 18));
        jCheckBox98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox98ActionPerformed(evt);
            }
        });

        jCheckBox99.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox99.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox99.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox99.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox100.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox100.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox100.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox100.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox101.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox101.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox101.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox101.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox102.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox102.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox102.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox102.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox103.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox103.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox103.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox103.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox104.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox104.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox104.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox104.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox105.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox105.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox105.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox105.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox106.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox106.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox106.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox106.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox107.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox107.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox107.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox107.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox108.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox108.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox108.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox108.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox109.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox109.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox109.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox109.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox110.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox110.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox110.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox110.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox111.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox111.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox111.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox111.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox112.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox112.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox112.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox112.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox113.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox113.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox113.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox113.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox114.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox114.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox114.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox114.setPreferredSize(new java.awt.Dimension(18, 18));

        jCheckBox115.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox115.setMaximumSize(new java.awt.Dimension(18, 18));
        jCheckBox115.setMinimumSize(new java.awt.Dimension(18, 18));
        jCheckBox115.setPreferredSize(new java.awt.Dimension(18, 18));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMaximumSize(new java.awt.Dimension(18, 18));
        jSeparator1.setMinimumSize(new java.awt.Dimension(18, 18));
        jSeparator1.setPreferredSize(new java.awt.Dimension(18, 18));

        jLabel1.setText(odkoduj(ak47));
        jLabel1.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel2.setText(odkoduj(aug));
        jLabel2.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel5.setText(odkoduj(barret));
        jLabel5.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel6.setText(odkoduj(binoculars));
        jLabel6.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel6.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel7.setText(odkoduj(magnum));
        jLabel7.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel8.setText(odkoduj(deagle));
        jLabel8.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel9.setText(odkoduj(dragunov));
        jLabel9.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel10.setText(odkoduj(flashbang));
        jLabel10.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel11.setText(odkoduj(g11));
        jLabel11.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel11.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel11.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel32.setText(odkoduj(g36));
        jLabel32.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel32.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel32.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel33.setText(odkoduj(glock));
        jLabel33.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel33.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel33.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel34.setText(odkoduj(granat));
        jLabel34.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel34.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel34.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel35.setText(odkoduj(m1014));
        jLabel35.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel35.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel35.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel36.setText(odkoduj(jackhamer));
        jLabel36.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel36.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel36.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel37.setText(odkoduj(m16));
        jLabel37.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel37.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel37.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel38.setText(odkoduj(mac));
        jLabel38.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel38.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel38.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel39.setText(odkoduj(makarov));
        jLabel39.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel39.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel39.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel40.setText(odkoduj(medipack));
        jLabel40.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel40.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel40.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel41.setText(odkoduj(mini));
        jLabel41.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel41.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel41.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel42.setText(odkoduj(mp5));
        jLabel42.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel42.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel42.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel43.setText(odkoduj(miny));
        jLabel43.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel43.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel43.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel44.setText(odkoduj(psg));
        jLabel44.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel44.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel44.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel45.setText(odkoduj(rpg));
        jLabel45.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel45.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel45.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel46.setText(odkoduj(law));
        jLabel46.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel46.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel46.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel47.setText(odkoduj(smg2));
        jLabel47.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel47.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel47.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel48.setText(odkoduj(smoke));
        jLabel48.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel48.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel48.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel49.setText(odkoduj(socom));
        jLabel49.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel49.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel49.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel50.setText(odkoduj(spas));
        jLabel50.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel50.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel50.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel51.setText(odkoduj(typka));
        jLabel51.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel51.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel51.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel52.setText(odkoduj(uzi));
        jLabel52.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel52.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel52.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel53.setText(odkoduj(twin));
        jLabel53.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel53.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel53.setPreferredSize(new java.awt.Dimension(90, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox98, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox99, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox105, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox107, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox108, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox109, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox114, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox115, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 20, Short.MAX_VALUE)
                                .addComponent(jCheckBox98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox115, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox107, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox112, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox114, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox113, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(20, 20, 20))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(20, 20, 20))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(20, 20, 20))
                                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jCheckBox63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jCheckBox64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(20, 20, 20))
                                                    .addComponent(jCheckBox65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20))
                                            .addComponent(jCheckBox66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20))
                                    .addComponent(jCheckBox67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addComponent(jCheckBox70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jCheckBox72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jCheckBox73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(20, 20, 20))
                                                    .addComponent(jCheckBox74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20))
                                            .addComponent(jCheckBox75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20))
                                    .addComponent(jCheckBox76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addComponent(jCheckBox79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        jScrollPane1.setViewportView(jPanel1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText(odkoduj(compile));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setText(odkoduj(orgfile));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(odkoduj(chosefile));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jToggleButton3.setText(odkoduj(seligi));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText(odkoduj(selcons));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(odkoduj(igi));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(odkoduj(cons));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText(odkoduj(selecttxt2));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText(odkoduj(selecttxt1));

        jButton4.setText(odkoduj(help));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(odkoduj(donate));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BanGun.copy("files\\orginal.qvm", "out\\weapon.qvm");
        BanGun.wczytajPlik();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ChoseFile ch = new ChoseFile();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BanGun.zapiszPlik();
        JOptionPane.showMessageDialog(this, "Compile Completed!\nGet your file from \"out\" directory");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        if(jToggleButton3.isSelected()){
            jToggleButton3.setText(odkoduj(deseligi));
                        	jCheckBox93.setSelected(true);
            	jCheckBox97.setSelected(true);
            	jCheckBox98.setSelected(true);
            	jCheckBox99.setSelected(true);
            	jCheckBox100.setSelected(true);
            	jCheckBox101.setSelected(true);
            	jCheckBox102.setSelected(true);
            	jCheckBox104.setSelected(true);
            	jCheckBox103.setSelected(true);
            	jCheckBox115.setSelected(true);
            	jCheckBox85.setSelected(true);
            	jCheckBox86.setSelected(true);
            	jCheckBox87.setSelected(true);
            	jCheckBox88.setSelected(true);
            	jCheckBox89.setSelected(true);
            	jCheckBox90.setSelected(true);
            	jCheckBox92.setSelected(true);
            	jCheckBox91.setSelected(true);
            	jCheckBox94.setSelected(true);
            	jCheckBox95.setSelected(true);
            	jCheckBox96.setSelected(true);
            	jCheckBox105.setSelected(true);
            	jCheckBox106.setSelected(true);
            	jCheckBox107.setSelected(true);
            	jCheckBox108.setSelected(true);
            	jCheckBox110.setSelected(true);
            	jCheckBox109.setSelected(true);
            	jCheckBox111.setSelected(true);
            	jCheckBox112.setSelected(true);
            	jCheckBox114.setSelected(true);
            	jCheckBox113.setSelected(true);

        }else{
            jToggleButton3.setText(odkoduj(seligi));
                jCheckBox93.setSelected(false);
            	jCheckBox97.setSelected(false);
            	jCheckBox98.setSelected(false);
            	jCheckBox99.setSelected(false);
            	jCheckBox100.setSelected(false);
            	jCheckBox101.setSelected(false);
            	jCheckBox102.setSelected(false);
            	jCheckBox104.setSelected(false);
            	jCheckBox103.setSelected(false);
            	jCheckBox115.setSelected(false);
            	jCheckBox85.setSelected(false);
            	jCheckBox86.setSelected(false);
            	jCheckBox87.setSelected(false);
            	jCheckBox88.setSelected(false);
            	jCheckBox89.setSelected(false);
            	jCheckBox90.setSelected(false);
            	jCheckBox92.setSelected(false);
            	jCheckBox91.setSelected(false);
            	jCheckBox94.setSelected(false);
            	jCheckBox95.setSelected(false);
            	jCheckBox96.setSelected(false);
            	jCheckBox105.setSelected(false);
            	jCheckBox106.setSelected(false);
            	jCheckBox107.setSelected(false);
            	jCheckBox108.setSelected(false);
            	jCheckBox110.setSelected(false);
            	jCheckBox109.setSelected(false);
            	jCheckBox111.setSelected(false);
            	jCheckBox112.setSelected(false);
            	jCheckBox114.setSelected(false);
            	jCheckBox113.setSelected(false);

        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jCheckBox98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox98ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox98ActionPerformed

    private void jCheckBox96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox96ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox96ActionPerformed

    private void jCheckBox86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox86ActionPerformed

    private void jCheckBox74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox74ActionPerformed

    private void jCheckBox65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox65ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        jCheckBox1.setSelected(true);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // cons
        if(jToggleButton4.isSelected()){
            jToggleButton4.setText(odkoduj(deselcons));
                jCheckBox1.setSelected(true);
            	jCheckBox2.setSelected(true);
            	jCheckBox3.setSelected(true);
            	jCheckBox4.setSelected(true);
            	jCheckBox5.setSelected(true);
            	jCheckBox6.setSelected(true);
            	jCheckBox7.setSelected(true);
            	jCheckBox9.setSelected(true);
            	jCheckBox8.setSelected(true);
            	jCheckBox63.setSelected(true);
            	jCheckBox64.setSelected(true);
            	jCheckBox65.setSelected(true);
            	jCheckBox66.setSelected(true);
            	jCheckBox67.setSelected(true);
            	jCheckBox68.setSelected(true);
            	jCheckBox69.setSelected(true);
            	jCheckBox71.setSelected(true);
            	jCheckBox70.setSelected(true);
            	jCheckBox72.setSelected(true);
            	jCheckBox73.setSelected(true);
            	jCheckBox74.setSelected(true);
            	jCheckBox75.setSelected(true);
            	jCheckBox76.setSelected(true);
            	jCheckBox77.setSelected(true);
            	jCheckBox78.setSelected(true);
            	jCheckBox80.setSelected(true);
            	jCheckBox79.setSelected(true);
            	jCheckBox81.setSelected(true);
            	jCheckBox82.setSelected(true);
            	jCheckBox84.setSelected(true);
            	jCheckBox83.setSelected(true);

        }else{
            jToggleButton4.setText(odkoduj(selcons));
            jCheckBox1.setSelected(false);
            	jCheckBox2.setSelected(false);
            	jCheckBox3.setSelected(false);
            	jCheckBox4.setSelected(false);
            	jCheckBox5.setSelected(false);
            	jCheckBox6.setSelected(false);
            	jCheckBox7.setSelected(false);
            	jCheckBox9.setSelected(false);
            	jCheckBox8.setSelected(false);
            	jCheckBox63.setSelected(false);
            	jCheckBox64.setSelected(false);
            	jCheckBox65.setSelected(false);
            	jCheckBox66.setSelected(false);
            	jCheckBox67.setSelected(false);
            	jCheckBox68.setSelected(false);
            	jCheckBox69.setSelected(false);
            	jCheckBox71.setSelected(false);
            	jCheckBox70.setSelected(false);
            	jCheckBox72.setSelected(false);
            	jCheckBox73.setSelected(false);
            	jCheckBox74.setSelected(false);
            	jCheckBox75.setSelected(false);
            	jCheckBox76.setSelected(false);
            	jCheckBox77.setSelected(false);
            	jCheckBox78.setSelected(false);
            	jCheckBox80.setSelected(false);
            	jCheckBox79.setSelected(false);
            	jCheckBox81.setSelected(false);
            	jCheckBox82.setSelected(false);
            	jCheckBox84.setSelected(false);
            	jCheckBox83.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("http://mariopl.weebly.com/donate.html"));
        } catch (URISyntaxException | IOException ex) {
            Loguj1.loguj("ChooseWeapons: donate: "+ex);
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Help h = new Help();
    }//GEN-LAST:event_jButton4ActionPerformed



    public static String odkoduj(String txt)
    {
        char[] tab = txt.toCharArray();
        char [] tab2 = new char[txt.length()/3];
        for(int i=0, j=txt.length()-1; i<tab2.length; i++,j-=3)
        {
            String l = tab[j]+""+tab[j-1]+""+tab[j-2];
            int x = Integer.parseInt(l);
            x = (int)Math.ceil(x/5.0);
            x=x-70;
            tab2[i] = (char)x; 
        }
        return new String(tab2);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public static javax.swing.JCheckBox jCheckBox1;
    public static javax.swing.JCheckBox jCheckBox100;
    public static javax.swing.JCheckBox jCheckBox101;
    public static javax.swing.JCheckBox jCheckBox102;
    public static javax.swing.JCheckBox jCheckBox103;
    public static javax.swing.JCheckBox jCheckBox104;
    public static javax.swing.JCheckBox jCheckBox105;
    public static javax.swing.JCheckBox jCheckBox106;
    public static javax.swing.JCheckBox jCheckBox107;
    public static javax.swing.JCheckBox jCheckBox108;
    public static javax.swing.JCheckBox jCheckBox109;
    public static javax.swing.JCheckBox jCheckBox110;
    public static javax.swing.JCheckBox jCheckBox111;
    public static javax.swing.JCheckBox jCheckBox112;
    public static javax.swing.JCheckBox jCheckBox113;
    public static javax.swing.JCheckBox jCheckBox114;
    public static javax.swing.JCheckBox jCheckBox115;
    public static javax.swing.JCheckBox jCheckBox2;
    public static javax.swing.JCheckBox jCheckBox3;
    public static javax.swing.JCheckBox jCheckBox4;
    public static javax.swing.JCheckBox jCheckBox5;
    public static javax.swing.JCheckBox jCheckBox6;
    public static javax.swing.JCheckBox jCheckBox63;
    public static javax.swing.JCheckBox jCheckBox64;
    public static javax.swing.JCheckBox jCheckBox65;
    public static javax.swing.JCheckBox jCheckBox66;
    public static javax.swing.JCheckBox jCheckBox67;
    public static javax.swing.JCheckBox jCheckBox68;
    public static javax.swing.JCheckBox jCheckBox69;
    public static javax.swing.JCheckBox jCheckBox7;
    public static javax.swing.JCheckBox jCheckBox70;
    public static javax.swing.JCheckBox jCheckBox71;
    public static javax.swing.JCheckBox jCheckBox72;
    public static javax.swing.JCheckBox jCheckBox73;
    public static javax.swing.JCheckBox jCheckBox74;
    public static javax.swing.JCheckBox jCheckBox75;
    public static javax.swing.JCheckBox jCheckBox76;
    public static javax.swing.JCheckBox jCheckBox77;
    public static javax.swing.JCheckBox jCheckBox78;
    public static javax.swing.JCheckBox jCheckBox79;
    public static javax.swing.JCheckBox jCheckBox8;
    public static javax.swing.JCheckBox jCheckBox80;
    public static javax.swing.JCheckBox jCheckBox81;
    public static javax.swing.JCheckBox jCheckBox82;
    public static javax.swing.JCheckBox jCheckBox83;
    public static javax.swing.JCheckBox jCheckBox84;
    public static javax.swing.JCheckBox jCheckBox85;
    public static javax.swing.JCheckBox jCheckBox86;
    public static javax.swing.JCheckBox jCheckBox87;
    public static javax.swing.JCheckBox jCheckBox88;
    public static javax.swing.JCheckBox jCheckBox89;
    public static javax.swing.JCheckBox jCheckBox9;
    public static javax.swing.JCheckBox jCheckBox90;
    public static javax.swing.JCheckBox jCheckBox91;
    public static javax.swing.JCheckBox jCheckBox92;
    public static javax.swing.JCheckBox jCheckBox93;
    public static javax.swing.JCheckBox jCheckBox94;
    public static javax.swing.JCheckBox jCheckBox95;
    public static javax.swing.JCheckBox jCheckBox96;
    public static javax.swing.JCheckBox jCheckBox97;
    public static javax.swing.JCheckBox jCheckBox98;
    public static javax.swing.JCheckBox jCheckBox99;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
