/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.mario.igi2_ranking;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateusz
 */
public class Glowne extends javax.swing.JFrame {

    static String startigi2 = "Ranking work only on Polski Serwer IGI2\n\nIf you have any mods you will be mark as \"MOD\" and it will not be able to change!\n\nDo you want to start IGI2?";
    boolean show;
    /**
     * Creates new form Glowne
     */
    public Glowne(String nick) throws FileNotFoundException {
        initComponents();
        Scanner filein = new Scanner(new File("ranking.cfg"));
        String checkbox = MarioEncoding.odkoduj(filein.nextLine());
        filein.close();
        if(checkbox.equals("true"))
            show = true;
        else
            show = false;
        jLabel2.setText(nick);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        changeprofil = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        startigi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IGI2 Ranking by Mario PL");
        setMinimumSize(new java.awt.Dimension(250, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Logged as:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Login");

        changeprofil.setText("Change profile");
        changeprofil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeprofilActionPerformed(evt);
            }
        });

        logout.setText("Exit");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        startigi.setText("Start");
        startigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startigiActionPerformed(evt);
            }
        });

        jButton1.setText("Donate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Stats:");

        jLabel4.setText("0");

        jLabel5.setText("/");

        jLabel6.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startigi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changeprofil))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startigi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeprofil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        if(!Main.player.getStats().isEmpty()){
            try {
                Web.sendPOST(Main.web+Links.score, Main.player.getLogin(), Main.player.getStats());
                Main.player.clrStats();
                HeartBeat.stop = false;
                Sniffer.stop = false;
                ModDetector.stop = false;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"Glowna: wyloguj: "+ ex);
            }
        }
        System.exit(0);
        
    }//GEN-LAST:event_logoutActionPerformed

    private void startigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startigiActionPerformed
        int odp = 0;
        if(!show){ 
            odp = JOptionPane.showConfirmDialog(this, startigi2 ,"Start IGI2", JOptionPane.OK_CANCEL_OPTION);
        }
        if(odp == 0){
            try {
                Main.starnRanking();
            } catch (IOException | InterruptedException ex) {
                JOptionPane.showMessageDialog(this,"Glowna: startIgi: "+ ex);
            } 
        }
        
        
    }//GEN-LAST:event_startigiActionPerformed

    private void changeprofilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeprofilActionPerformed
        try {
            Desktop.getDesktop().browse(new URI(Main.web+Links.profile));
        } catch (IOException | URISyntaxException ex) {
            JOptionPane.showMessageDialog(this, "Change profile: "+ex);
        } 
    }//GEN-LAST:event_changeprofilActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(!Main.player.getStats().isEmpty()){
            try {
                Web.sendPOST(Main.web+"Score", Main.player.getLogin(), Main.player.getStats());
                Main.player.clrStats();
                HeartBeat.stop = false;
                Sniffer.stop = false;
                System.exit(0);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"Glowna: wyloguj: "+ ex);
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            Desktop.getDesktop().browse(new URI(Main.web+Links.donate));
        } catch (IOException | URISyntaxException ex) {
            JOptionPane.showMessageDialog(this, "Donate: "+ex);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

 
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeprofil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JButton logout;
    private javax.swing.JButton startigi;
    // End of variables declaration//GEN-END:variables
}
